### ISSUE TITLE
[Enhancement] 结合johnny老师脚本和小姐姐的插件，提出的一些小建议

### ISSUE THREAD

**Issue by xjtusjtu** [romantic-black/obsidain-vika-sync#11]
以下只是给作者小姐姐的一些小建议，小姐姐可以自己考虑是否有必要加到插件当中。无论结果如何，非常感谢小姐姐幸苦做出来的插件！

**1** 自定义UID field

OBURI的其中uid字段，是否可以像Advanced URI插件中的设置【UID field in frontmatter 】那样，允许使用者自定义 UID字段，在YAML区使用 ”UID“、”Uid“、”id“ 等字段，或者是默认Vika中必须上传的”ID“字段，最终的效果是允许OBURI的网址是 obsidian://advanced-uri?vault=Obsidian_demo&**<自定义字段>**=recH5T17h5Cq1，例如 "obsidian://advanced-uri?vault=Obsidian_demo&**UID**=recH5T17h5Cq1"

---

**2** 保留aliases在OB的YAML区中的英文单引号

原因：我之所以会在aliases字段的值两边加上单引号，是因为这样会允许它的值中包含特殊的英文符号，例如英文冒号`:`，英文短横线`-`，英文双引号`"`。根本原因是一些英文网站、英文文献会有副标题，副标题和主标题之前常用这些特殊符号连接

理想效果：
- 保留aliases在OB的YAML区中的英文单引号（甚至一开始没有写，上传后在OB的YAML区强制加上左右单引号）
    - 别名如果包含特殊字符，加上单引号后，既可以在OB当中正常显示，也可以成功上传vika；如果没有单引号，在OB中无法正常显示，而且执行上传Vika的命令后，（由于是无效的aliases）OB当中会直接丢失，而Vika中也没有该别名
- 同时不让Vika字段显示强制加上的引号（会有一点影响美观）

上传前OB的YAML区

```
aliases: 
 - 'Monetary Incentives and Knowledge Spillover: Evidence from a Natural Experiment'
```

上传后OB的YAML区（单引号没了）
```
aliases: 
 - Monetary Incentives and Knowledge Spillover: Evidence from a Natural Experiment
```

---

**3** 关于Vika当中的【日期】类型

如果上传的是日期，并在Vika当中设置为了【日期】类型，那么在运行【Vika Sync: Update this Note】后，该字段对应值会变为数字（参见下方），这样不利于在OB中观察和修改具体日期，需要进行相应处理

理想效果：OB的YAML区该日期字段仍然是日期而不是数字

上传前YAML区

```
published_date: 2022-05
```

上传后YAML区

```
published_date: 1651334400000
```

---

**4** Vika当中保留库名中的空格

如果OB的库名当中带有空格，上传至Vika后会显示为 "%20"

这个是Johnny老师的脚本中的一个小问题，我并没有确认是否在小姐姐的插件中也存在这个问题

解决办法：上传到Vika的字段使用 `decodeURI()` 方法处理一下，即

```
Vault: decodeURI(this.vault)
```

---

下面我个人使用的一些自定义字段

```json
{
	"level": "",
	"published_date": "2022-01",
	"citations": 0,
	"rating": "⭐"
}
```

最后再次感谢小姐姐的幸苦付出！

**Comment by romantic-black** [comment]
2：我读取 aliases 和 tags 的方式都是用 obsidian 的 api，也就是说 ob 会在读取 frontmatter 自动将字符串的单引号删去，这块感觉不是很好解决，除非重写一种读取 frontmatter 的方式
3：转换日期这个可以考虑，但应该只会转换默认字段里 update 和 create，当下载项有它们时会被转换成时间格式
4：下个版本改
1：我觉得意义可能不大吧，虽然改起来也不难

**Comment by xjtusjtu** [comment]
谢谢小姐姐回复~
