### ISSUE TITLE
frontmatter中的多行文本无法同步到vika

### ISSUE THREAD

**Issue by Tenstu** [romantic-black/obsidain-vika-sync#12]
疑似bug，在插件中添加自定义字段并设置vika对应列后，设置为字符串文本类型的字段无法被识别同步。例如添加citekey和PaperName两个字段后，{"citekey":[],"PaperName":""} ，其中仅以数组格式的可以被同步到vika，字符串类型的无论字符长短，有无空格，均无法同步或更新，使用的为最新的0.27release，麻烦看下如何解决。

**Comment by romantic-black** [comment]
要不你加下微信我远程看一下

**Comment by Tenstu** [comment]
> 要不你加下微信我远程看一下

谢谢，方便的话 请添加微信号：zxh6789ten
