### ISSUE TITLE
小小建议

### ISSUE THREAD

**Issue by zhangym** [romantic-black/obsidain-vika-sync#6]
首先为大神真么快，能开发这么棒的插件点赞、摩拜
一些小建议：
1. 关于OB frontmatter  属性值
（1）Tags，Aliases的首字母也和其他属性一样统一为小写，即tags，aliases。
（2）增加对常见标签如tag（含Tag、Tags），alias（含Alias、Aliases）的自动合并和容错检测。

2.关于vika字段
建议CreatedTime、UpdatedTime 使用日期型（包含24小时制时间），便于后期再利用。

**Comment by romantic-black** [comment]
1.1 用 Tags 主要是因为 Johnny 老师的脚本里就是 Tags，这个可以后期讨论一下看看用大写还是小写
1.2 改了已经
2 你在 vika 中把那两个字段设为日期型就可以
