### ISSUE TITLE
关于命令与功能方面的建议

### ISSUE THREAD

**Issue by zhangym** [romantic-black/obsidain-vika-sync#9]
1. `recover Record` 建议 改为 `Recover Record` 与其他的一致。
2.  `Create Record` 和 `Update Record` 建议合二为一，存在就Update，不存在就Create，减少命令个数，将来设置快捷键也容易

**Comment by zhangym** [comment]
目前对已有笔记使用`Create Record`在vika中产生一条一模一样的Record

**Comment by romantic-black** [comment]
1. 下个版本会改
2. 现在的功能其实就是你建议的那样，我可能会给 Create 改个名，叫 `Create New Record` 更合适一点

**Comment by zhangym** [comment]
Ob→Vika   或 Ob↑Vika     Ob2Vika   `Ob to Vika`
Vika→OB  或 Vika↓OB   Vika2OB      `Vika to OB`

Ob→Vika in Folder

Ob→Vika in Vault

Delete Current Note in OB&Vika （Record 是 vika 术语）

**Comment by zhangym** [comment]
Update Current Note：当前Note to Vika没有则Create，有则update

Update All Note in the Folder

Update All Note in the Vault

未来：
Pull Note(s) From Vika：支持vika相关字段查询

**Comment by romantic-black** [comment]
我想的是在 ob 的文件侧边栏里右键某个文件夹，然后点击一个命令获取 vika 里该文件夹的所有笔记，因为有个 folder的字段

**Comment by vivi2221li** [comment]
按了全部update的按键后，有出现不能全部更新的bug，然后在obsidian的一些标签没有办法在标签栏显示，同时如果有些文件搞错了，不要上传上去，结果上传后，没有办法撤销操作或者还原部分。

**Comment by romantic-black** [comment]
> 按了全部update的按键后，有出现不能全部更新的bug，然后在obsidian的一些标签没有办法在标签栏显示，同时如果有些文件搞错了，不要上传上去，结果上传后，没有办法撤销操作或者还原部分。

不能全部更新是因为vika对api的操作有限制，这个我也没办法，以后可能会删除全部更新的功能
标签栏不能显示的具体是哪些
最后第三部分有点没懂
